### ISSUE TITLE
Перестал запускатся

### ISSUE THREAD

**Issue by Volcharka** [TiberiumN/VBot#29]
Сразу после запуска выдает
```
←[35m11:55:42←[0m - ←[31mERROR←[0m - ←[39mПроизошла фатальная ошибка во время работы:
←[0m
Traceback (most recent call last):
  File "vbot.py", line 264, in <module>
    loop.run_until_complete(bot.run(loop))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 466, in run_u
ntil_complete
    return future.result()
  File "vbot.py", line 210, in run
    await self.init_long_polling()
  File "vbot.py", line 111, in init_long_polling
    {'use_ssl': 1})
  File "C:\Users\Administrator\Desktop\VBot-master\vkplus.py", line 218, in method
    return await api_method(key, **data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\api.py", line 9, in __c
all__
    return await getattr(self, method_name)(**method_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\api.py", line 25, in __
call__
    return await self._api._session.make_request(self, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\sessions.py", line 24,
in make_request
    return await self.send_api_request(method_request._method_name, params, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\sessions.py", line 45,
in send_api_request
    await self.authorize()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\sessions.py", line 81,
in authorize
    html = await self.get_auth_page()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\sessions.py", line 109,
 in get_auth_page
    status, response = await self.driver.get_text(self.AUTH_URL, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\utils.py", line 28, in
wrapper
    return await func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\mixins.py", line 18, in get_text
    return await super().get_text(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\aiovk\drivers.py", line 82, in get_text
    return response.status, await response.text()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\async_timeout\__init__.py", line 44, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

**Comment by DiSonDS** [comment]
Плюсую

**Comment by TiberiumN** [comment]
@DiSonDS вместо "Плюсую" можно выбрать +1 к посту, чтобы не захламлять комментарии :)

**Comment by DiSonDS** [comment]
@TiberiumN  С телефона писал, там данной фичи нет

**Comment by TiberiumN** [comment]
@DiSonDS всегда есть фулл версия :)

**Comment by DiSonDS** [comment]
@TiberiumN 
Кстати, у меня эта ошибка сама по себе пропала и бот теперь запускается. Если у @Volcharka тоже все хорошо, то можно закрывать.

**Comment by TiberiumN** [comment]
@DiSonDS это проблемы вк, как всегда

**Comment by Volcharka** [comment]
@TiberiumN  Уже все нормально, но проблема с лонгпуллом осталась https://github.com/TiberiumN/VBot/issues/26

**Comment by ismayil159** [comment]
У меня вот именно такая ошибка Warning: Function vk.init_longpoll will be removed replace with vk.longpoll.star

**Comment by Yardanico** [comment]
@ismayil159 Это не ошибка, а предупреждение
